# Generated by Django 4.0.3 on 2022-05-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameNew', models.TextField(default='')),
                ('Age', models.TextField(default='')),
                ('Address', models.TextField(default='')),
                ('Birthday', models.TextField(default='')),
            ],
        ),
    ]
