# Generated by Django 4.0.3 on 2022-07-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContrerasList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminu', models.TextField(default='')),
                ('adminp', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nFullName', models.TextField(default='')),
                ('nAddress', models.TextField(default='')),
                ('aage', models.IntegerField(default='0')),
                ('nGenders', models.TextField(default='')),
                ('acontumber', models.IntegerField(default='0')),
                ('aemailAddress', models.TextField(default='')),
                ('agname', models.TextField(default='')),
                ('asoi', models.TextField(default='')),
                ('nAIncome', models.IntegerField(default='0')),
                ('ausername', models.TextField(default='')),
                ('apassword', models.TextField(default='')),
                ('sstatus', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NMSchool', models.TextField(default='')),
                ('slevel', models.TextField(default='')),
                ('nStudentId', models.TextField(default='')),
                ('nGPA', models.IntegerField(default='0')),
                ('sid', models.ImageField(default='', upload_to='')),
                ('sgwa', models.ImageField(default='', upload_to='')),
                ('applicant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ContrerasList.applicant')),
            ],
        ),
        migrations.DeleteModel(
            name='InfoForm',
        ),
    ]
